baseURL = 'https://www.borgeirgens.no/'
languageCode = 'no-nb'
title = 'Personlig blog'
theme = 'ananke'

[taxonomies]
  tag = 'tags'
  project = 'projects'

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Om"
  url = "/om/"
  weight = 2
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3
