name: Build and deploy personal website

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Git submodule update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.121.2
        run: |
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Build website
        id: build
        run: |
          hugo

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.BUILD_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.HOST_KEY }}" > ~/.ssh/known_hosts
          echo "Host borgeirgens.no
              Hostname ssh.borgeirgens.no
              user build
              IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config

      - name: deploy
        run: ./deploy.sh
